name: Deploy to Firebase (hosting + functions)

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ---------- DIAG FRONTEND PATH ----------
      - name: Show repo root
        run: |
          pwd
          ls -la

      - name: Show frontend folder
        run: |
          ls -la the-turnstile-nextjs
          cat the-turnstile-nextjs/package.json

      # ---------- FRONTEND ----------
      - name: Install frontend deps
        working-directory: the-turnstile-nextjs
        run: npm install --no-audit --no-fund

      - name: Verify Next installed
        working-directory: the-turnstile-nextjs
        run: npx next --version

      - name: Build static export
        working-directory: the-turnstile-nextjs
        run: npm run build

      - name: List export
        run: ls -la the-turnstile-nextjs/out

      # ---------- BACKEND ----------
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install functions deps
        working-directory: functions
        run: npm install --no-audit --no-fund

      - name: Build functions
        working-directory: functions
        run: npm run build

      # ---------- DEPLOY ----------
      - name: Auth for deploy
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json

      - name: Deploy hosting + functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
        run: firebase deploy --only hosting,functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
