name: Deploy to Firebase (hosting + functions)

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ---- Detect the Next.js app directory automatically ----
      - name: Detect FRONTEND_DIR
        id: detect
        run: |
          echo "Searching for a package.json that depends on Next…"
          CANDIDATES=$(grep -Rsl '"next":' -n */package.json || true)
          echo "Candidates:"
          echo "${CANDIDATES}"
          FRONTEND_DIR=$(dirname $(echo "${CANDIDATES}" | head -n1))
          if [ -z "${FRONTEND_DIR}" ]; then
            echo "No Next app found. Fail."
            exit 1
          fi
          echo "FRONTEND_DIR=${FRONTEND_DIR}" | tee -a $GITHUB_ENV

      - name: Show detected FRONTEND_DIR
        run: |
          echo "FRONTEND_DIR=$FRONTEND_DIR"
          ls -la "$FRONTEND_DIR"
          cat "$FRONTEND_DIR/package.json"

      # ---- FRONTEND (install + build) ----
      - name: Install frontend deps
        run: npm --prefix "$FRONTEND_DIR" install --no-audit --no-fund

      - name: Verify Next installed
        run: |
          npx --prefix "$FRONTEND_DIR" next --version
          ls -la "$FRONTEND_DIR/node_modules/.bin" || true

      - name: Build static export
        run: npm --prefix "$FRONTEND_DIR" run build

      - name: List export
        run: ls -la "$FRONTEND_DIR/out" || true

      # ---- BACKEND (functions) ----
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install functions deps
        run: npm --prefix functions install --no-audit --no-fund

      - name: Build functions
        run: npm --prefix functions run build

      # ---- DEPLOY ----
      - name: Auth for deploy
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json

      - name: Deploy hosting + functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
        run: |
          # Use the detected frontend dir for Hosting
          # Ensure firebase.json points to "$FRONTEND_DIR/out"
          cat firebase.json
          firebase deploy --only hosting,functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
