name: Deploy staging branch to Firebase Hosting

on:
  push:
    branches:
      - staging

permissions:
  contents: read
  id-token: write

concurrency:
  group: staging-deployment
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: the-turnstile-nextjs

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: the-turnstile-nextjs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting (staging)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_SCRUM_BOOK }}
          projectId: the-scrum-book
          channelId: staging-site
          expires: '7d'
