name: Deploy to Firebase (hosting + functions)

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            the-turnstile-nextjs/package-lock.json
            functions/package-lock.json

      # Frontend
      - name: Install frontend deps
        working-directory: the-turnstile-nextjs
        run: npm ci || npm install

      - name: Build static export
        working-directory: the-turnstile-nextjs
        run: npm run build

      - name: List export
        run: ls -la the-turnstile-nextjs/out

      # Backend
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install functions deps
        working-directory: functions
        run: npm ci || npm install

      - name: Build functions
        working-directory: functions
        run: npm run build

      # Deploy
      - name: Auth for deploy
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json

      - name: Deploy hosting + functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
        run: firebase deploy --only hosting,functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
