# ---------- DIAG ----------
- name: Show repo root
  run: |
    pwd
    ls -la

- name: Show frontend folder
  run: |
    ls -la the-turnstile-nextjs || true
    test -f the-turnstile-nextjs/package.json && cat the-turnstile-nextjs/package.json || echo "package.json not found"

# ---------- FRONTEND ----------
- name: Install frontend deps
  run: npm --prefix the-turnstile-nextjs install --no-audit --no-fund

- name: Verify Next installed
  run: npx --prefix the-turnstile-nextjs next --version

- name: Build static export
  run: npm --prefix the-turnstile-nextjs run build

- name: List export
  run: ls -la the-turnstile-nextjs/out || true
