name: Deploy to Firebase (hosting + functions)

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ---- DIAG: confirm paths ----
      - name: Show repo root
        run: |
          pwd
          ls -la

      - name: Show frontend folder
        run: |
          ls -la the-turnstile-nextjs || true
          test -f the-turnstile-nextjs/package.json && cat the-turnstile-nextjs/package.json || echo "package.json NOT FOUND"

      # ---- FRONTEND ----
      - name: Install frontend deps
        run: npm --prefix the-turnstile-nextjs install --no-audit --no-fund

      - name: Verify Next installed
        run: npx --prefix the-turnstile-nextjs next --version

      - name: Build static export
        run: npm --prefix the-turnstile-nextjs run build

      - name: List export
        run: ls -la the-turnstile-nextjs/out || true

      # ---- BACKEND ----
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install functions deps
        run: npm --prefix functions install --no-audit --no-fund

      - name: Build functions
        run: npm --prefix functions run build

      # ---- DEPLOY ----
      - name: Auth for deploy
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json

      - name: Deploy hosting + functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
        run: firebase deploy --only hosting,functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
