name: Deploy to Firebase (hosting + functions)

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Detect frontend app folder
      - name: Detect Next.js folder
        id: detect
        run: |
          echo "Searching for Next.js package.json..."
          FOUND=$(grep -Rsl '"next"' -n */package.json || true)
          echo "$FOUND"
          APP_DIR=$(dirname $(echo "$FOUND" | head -n1))
          if [ -z "$APP_DIR" ]; then
            echo "No Next.js folder found"; exit 1
          fi
          echo "FRONTEND_DIR=$APP_DIR" | tee -a $GITHUB_ENV

      - name: Show detected folder
        run: |
          echo "Detected: $FRONTEND_DIR"
          ls -la "$FRONTEND_DIR"
          cat "$FRONTEND_DIR/package.json"

      # Install and build frontend
      - name: Install frontend dependencies
        run: npm --prefix "$FRONTEND_DIR" install --no-audit --no-fund

      - name: Verify Next.js installation
        run: npx --prefix "$FRONTEND_DIR" next --version

      - name: Build static export
        run: npm --prefix "$FRONTEND_DIR" run build

      - name: List build output
        run: ls -la "$FRONTEND_DIR/out" || true

      # Firebase setup
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install functions dependencies
        run: npm --prefix functions install --no-audit --no-fund

      - name: Build Cloud Functions
        run: npm --prefix functions run build

      # Authenticate using GitHub secret
      - name: Authenticate to Firebase
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      # Deploy both hosting + functions
      - name: Deploy to Firebase
        run: firebase deploy --only hosting,functions --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive
