name: Deploy to Firebase (hosting + functions)

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ---- DIAG: confirm paths/files ----
      - name: Show repo root
        run: |
          pwd
          ls -la
          echo "----------"
          find . -maxdepth 3 -type f -name package.json -print

      - name: Show frontend folder
        run: |
          if [ -d the-turnstile-nextjs ]; then ls -la the-turnstile-nextjs; else echo "MISSING: the-turnstile-nextjs"; fi
          if [ -f the-turnstile-nextjs/package.json ]; then cat the-turnstile-nextjs/package.json; else echo "MISSING: the-turnstile-nextjs/package.json"; fi

      # ---- FRONTEND (FORCE FOLDER WITH --prefix) ----
      - name: Install frontend deps
        run: npm --prefix the-turnstile-nextjs install --no-audit --no-fund

      - name: Verify Next installed
        run: |
          npx --prefix the-turnstile-nextjs next --version
          npm --prefix the-turnstile-nextjs ls next

      - name: Build static export
        run: npm --prefix the-turnstile-nextjs run build

      - name: List export
        run: ls -la the-turnstile-nextjs/out || true

      # ---- BACKEND ----
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
